#!/usr/bin/env python3
import sys
import os
import helpers
from analyzer import Analyzer
from termcolor import colored

if len(sys.argv) != 2:
    sys.exit("Usage: ./smile word")

app = sys.argv[1].lstrip("@")

positives = os.path.join(sys.path[0], "positive-words.txt")
negatives = os.path.join(sys.path[0], "negative-words.txt")

tweets = helpers.get_user_timeline(app, 50)

if tweets == None:
    sys.exit("Error, unable to access user's tweets")

analyzer = Analyzer(positives, negatives)

for tweet in tweets:
    c = analyzer.analyze(tweet)

    if c > 0:
        print(colored(":)", "green"))
    elif c < 0:
        print(colored(":(", "red"))
    else:
        print(colored(":|", "yellow"))